In [50]:
import pandas as pd
df_x = pd.read_excel('../data/FCFC_ARO_900/R911R912 _ARO1_R2.xlsx',sheet_name='R911R912_TAG相關錶點資料(X)')
df_x

,Unnamed: 0,Unnamed: 1,ARO1-DCS-FIC_91103_2,ARO1-DCS-FIC_91103_1,ARO1-DCS-FI_91203,ARO1-DCS-FIC_98102_1,ARO1-DCS-FIC_98102_1.RESULT,ARO1-DCS-FIC_98302_1,ARO1-DCS-FIC_98302_1.RESULT,ARO1-DCS-FIC_98401_1,...,Unnamed: 55,ARO1-LIMS-S704-BR_INDEX,ARO1-LIMS-s704-744-C9,ARO1-LIMS-s704-744-C10+,ARO1-LIMS-S704-WATER,ARO1-LIMS-S704-TS,Unnamed: 61,ARO1-LIMS-s909-744-C9,ARO1-LIMS-s909-744-C10+,ARO1-LIMS-S909-BR_INDEX
0,NaN,2013-07-20 00:00:00,638.648,638.326,645.39,12.7533,12.621,224.999,226.57,233.111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,2013-07-20 01:00:00,651.542,653.594,634.265,12.7533,12.5872,224.999,226.244,233.111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,2013-07-20 02:00:00,648.831,647.641,657.156,12.7533,12.6072,224.999,226.425,233.111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,2013-07-20 03:00:00,622.012,624.454,654.175,12.7533,12.5788,224.999,226.658,233.111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,2013-07-20 04:00:00,671.924,668.433,659.25,12.7533,12.5766,224.999,226.442,233.111,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71443,NaN,2021-09-12 19:00:00,722.191,725.545,731.913,14.3822,14.3562,254.993,251.556,271.035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71444,NaN,2021-09-12 20:00:00,718.417,721.381,732.752,14.3822,14.3629,254.993,251.453,271.035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71445,NaN,2021-09-12 21:00:00,718.555,721.612,734.14,14.3822,14.3511,254.993,251.528,271.035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71446,NaN,2021-09-12 22:00:00,718.663,721.005,731.884,14.3822,14.3464,254.993,251.578,271.035,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71447,NaN,2021-09-12 23:00:00,717.995,720.603,728.597,14.3822,14.3534,254.993,251.472,271.035,...,NaN,0.94,67.0,0.0,35.23,0.01,NaN,NaN,NaN,NaN

In [51]:
dic = {
    "ARO1-DCS-FIC_91103_1":"二號到一號吸附室流量",
    "ARO1-DCS-FI_91203":"一號到二號吸附室流量",
    "ARO1-DCS-FIC_98302_1":"RV進料油量",
    "ARO1-DCS-FIC_98401_1":"RV脫附劑流量",
    "ARO1-DCS-FI_91701":"萃餘塔流量",
    "ARO1-DCS-FIC_92001_1":"萃取塔流量",
    "ARO1-LIMS-S704-BR_INDEX":"進料溴指數",
    "ARO1-LIMS-s704-744-C9":"進料A9含量",
    "ARO1-LIMS-s704-744-C10+":"進料A10含量",
    "ARO1-LIMS-S704-WATER":"進料含水量",
    "ARO1-LIMS-S704-TS":"進料硫含量",
    "ARO1-LIMS-S917-WATER":"萃餘油水份含量",
    "ARO1-LIMS-S916-WATER":"萃取油水份含量",
    "ARO1-DCS-PDI_91102":"R911吸附室壓差",
    "ARO1-DCS-PDI_91202":"R912吸附室壓差",
    "ARO1-DCS-AC_A_FA":"FA",
    "ARO1-DCS-AC_HF":"HA",
    "ARO1-DCS-AC_L2_A":"L2",
    "ARO1-DCS-AC_L3_A":"L3",
    "ARO1-DCS-AC_L4_A":"L4",
    "ARO1-DCS-AC_XF":"XF",
    "ARO1-LIMS-s912-744-p-Xylene":"PX產品PX含量",
    "ARO1-LIMS-s912-744-m-Xylene":"PX產品MX含量",
    "ARO1-LIMS-s917-744-p-Xylene":"萃取油PX含量",
    "ARO1-LIMS-s916-744-p-Xylene":"萃餘油PX含量",
    "ARO1-DCS-PX 回收率":"PX回收率"
}



dic = {
    "ARO2-DCS-FI914A2":"二號到一號吸附室流量",
    "ARO2-DCS-FI914A3":"一號到二號吸附室流量",
    "ARO2-DCS-FI91601":"RV進料油量",
    "ARO2-DCS-FI91701":"RV脫附劑流量",
    "ARO2-DCS-FI93201":"萃餘塔流量",
    "ARO2-DCS-FI94701":"萃取塔流量",
    "ARO2-LIMS-S708@Br.Index":"進料溴指數",
    "ARO2-LIMS-S708@A9":"進料A9含量",
    "ARO2-LIMS-S708@A10+":"進料A10含量",
    "ARO2-LIMS-S708@Water":"進料含水量",
    "ARO2-LIMS-S708@Sulfur":"進料硫含量",
    "ARO2-LIMS-S905@Water":"萃餘油水份含量",
    "ARO2-LIMS-S907@Water":"萃取油水份含量",
    "ARO2-DCS-PDI91101":"R911吸附室壓差",
    "ARO2-DCS-PDI91201":"R912吸附室壓差",
    "ARO2-DCS-R911_2_A_FA":"FA",
    "ARO2-DCS-R911_2_HF":"HA",
    "ARO2-DCS-R911_2_L2_A":"L2",
    "ARO2-DCS-R911_2_L3_A":"L3",
    "ARO2-DCS-R911_2_L4_A":"L4",
    "ARO2-DCS-R911_2_XF":"XF",
    "ARO2-LIMS-s922@PX":"PX產品PX含量",
    "ARO2-LIMS-s922@MX":"PX產品MX含量",
    "ARO2-LIMS-S907@PX":"萃取油PX含量",
    "ARO2-LIMS-S905@PX":"萃餘油PX含量",
    "ARO2-DCS-PX@Recovery":"PX回收率"
}

In [52]:
s_col = ['ARO1-DCS-FIC_98302_1','ARO1-DCS-FIC_98401_1',
'ARO1-DCS-AC_CTIME','ARO1-DCS-AC_STIME',
'ARO1-LIMS-S704-BR_INDEX','ARO1-LIMS-s704-744-C9',
'ARO1-LIMS-s704-744-C10+','ARO1-LIMS-S704-WATER',
'ARO1-LIMS-S704-TS']
a_col = ['ARO1-DCS-AC_L2_A','ARO1-DCS-AC_L3_A','ARO1-DCS-AC_L4_A','ARO1-DCS-AC_A_FA','ARO1-DCS-AC_HF']

In [53]:
df_x[s_col]

,ARO1-DCS-FIC_98302_1,ARO1-DCS-FIC_98401_1,ARO1-DCS-AC_CTIME,ARO1-DCS-AC_STIME,ARO1-LIMS-S704-BR_INDEX,ARO1-LIMS-s704-744-C9,ARO1-LIMS-s704-744-C10+,ARO1-LIMS-S704-WATER,ARO1-LIMS-S704-TS
0,224.999,233.111,33.1633,82.9083,NaN,NaN,NaN,NaN,NaN
1,224.999,233.111,33.1633,82.9083,NaN,NaN,NaN,NaN,NaN
2,224.999,233.111,33.1633,82.9083,NaN,NaN,NaN,NaN,NaN
3,224.999,233.111,33.1633,82.9083,NaN,NaN,NaN,NaN,NaN
4,224.999,233.111,33.1633,82.9083,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
71443,254.993,271.035,29.4369,73.5924,NaN,NaN,NaN,NaN,NaN
71444,254.993,271.035,29.4369,73.5924,NaN,NaN,NaN,NaN,NaN
71445,254.993,271.035,29.4369,73.5924,NaN,NaN,NaN,NaN,NaN
71446,254.993,271.035,29.4369,73.5924,NaN,NaN,NaN,NaN,NaN
71447,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01

In [54]:
df_x[a_col]

,ARO1-DCS-AC_L2_A,ARO1-DCS-AC_L3_A,ARO1-DCS-AC_L4_A,ARO1-DCS-AC_A_FA,ARO1-DCS-AC_HF
0,0.429883,1.54015,-0.510051,0.485,120.012
1,0.429883,1.54015,-0.510051,0.485,120.012
2,0.429883,1.54015,-0.510051,0.485,120.012
3,0.429883,1.54015,-0.510051,0.485,120.012
4,0.429839,1.54015,-0.510051,0.485,120.012
...,...,...,...,...,...
71443,0.398877,1.54006,-0.579923,0.482027,120.012
71444,0.398877,1.54006,-0.579923,0.482027,120.012
71445,0.398877,1.54006,-0.579923,0.482027,120.012
71446,0.398877,1.54006,-0.579923,0.482027,120.012
71447,0.398877,1.54006,-0.579923,0.482027,120.012

In [55]:
df_y = pd.read_excel('../data/FCFC_ARO_900/R911R912 _ARO1_R2.xlsx',sheet_name='目標值(Y)相關錶點資料')
df_y

,Unnamed: 0,ARO1-LIMS-s704-744-p-Xylene,ARO1-LIMS-s912-744-Ethylbz,ARO1-LIMS-s912-744-p-Xylene,ARO1-LIMS-s912-744-m-Xylene,ARO1-LIMS-s912-744-o-Xylene,ARO1-DCS-PX 回收率,ARO1-LIMS-s917-744-p-Xylene,ARO1-LIMS-s916-744-p-Xylene
0,2013-07-20 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2013-07-20 01:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2013-07-20 02:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2013-07-20 03:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013-07-20 04:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
71443,44451.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71444,44451.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71445,44451.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71446,44451.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71447,44452,23.5889,557.0,99.7211,1597.0,442.0,96.4098,NaN,NaN

In [56]:
y_col = []
for i in df_y.columns:
    if 'Unnamed' not in i:
        y_col.append(i)
y_col

['ARO1-LIMS-s704-744-p-Xylene',
 'ARO1-LIMS-s912-744-Ethylbz',
 'ARO1-LIMS-s912-744-p-Xylene',
 'ARO1-LIMS-s912-744-m-Xylene',
 'ARO1-LIMS-s912-744-o-Xylene',
 'ARO1-DCS-PX 回收率',
 'ARO1-LIMS-s917-744-p-Xylene',
 'ARO1-LIMS-s916-744-p-Xylene']

In [57]:
# 選一個示範使用
y_col = ['ARO1-DCS-PX 回收率']

In [58]:
def get_interval(df,col):
    interval = []
    for t,i in enumerate(df[col]):
        if str(i) != 'nan':
            interval.append(t)
    interval = [ i-j for i,j in zip(interval[1:],interval[:-1])]
    return max(interval,key=interval.count)
get_interval(df_y,y_col[0])

8

In [59]:
df_xy = df_x[s_col+a_col].join(df_y[y_col])
df_xy[s_col+a_col] = df_xy[s_col+a_col].fillna(method='bfill')
df_xy

,ARO1-DCS-FIC_98302_1,ARO1-DCS-FIC_98401_1,ARO1-DCS-AC_CTIME,ARO1-DCS-AC_STIME,ARO1-LIMS-S704-BR_INDEX,ARO1-LIMS-s704-744-C9,ARO1-LIMS-s704-744-C10+,ARO1-LIMS-S704-WATER,ARO1-LIMS-S704-TS,ARO1-DCS-AC_L2_A,ARO1-DCS-AC_L3_A,ARO1-DCS-AC_L4_A,ARO1-DCS-AC_A_FA,ARO1-DCS-AC_HF,ARO1-DCS-PX 回收率
0,224.999,233.111,33.1633,82.9083,1.22,72.0,0.0,26.76,0.01,0.429883,1.54015,-0.510051,0.485,120.012,NaN
1,224.999,233.111,33.1633,82.9083,1.22,72.0,0.0,26.76,0.01,0.429883,1.54015,-0.510051,0.485,120.012,NaN
2,224.999,233.111,33.1633,82.9083,1.22,72.0,0.0,26.76,0.01,0.429883,1.54015,-0.510051,0.485,120.012,NaN
3,224.999,233.111,33.1633,82.9083,1.22,72.0,0.0,26.76,0.01,0.429883,1.54015,-0.510051,0.485,120.012,NaN
4,224.999,233.111,33.1633,82.9083,1.22,72.0,0.0,26.76,0.01,0.429839,1.54015,-0.510051,0.485,120.012,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71443,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01,0.398877,1.54006,-0.579923,0.482027,120.012,NaN
71444,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01,0.398877,1.54006,-0.579923,0.482027,120.012,NaN
71445,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01,0.398877,1.54006,-0.579923,0.482027,120.012,NaN
71446,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01,0.398877,1.54006,-0.579923,0.482027,120.012,NaN
71447,254.993,271.035,29.4369,73.5924,0.94,67.0,0.0,35.23,0.01,0.398877,1.54006,-0.579923,0.482027,120.012,96.4098

In [60]:
from tqdm import tqdm
for i in tqdm(df_xy.columns):
    df_xy[i] = pd.to_numeric(df_xy[i],errors='coerce')

100%|██████████| 15/15 [00:00<00:00, 134.10it/s]

In [61]:
from sklearn.preprocessing import MinMaxScaler

mm_a = MinMaxScaler()
mm_s = MinMaxScaler()
mm_y = MinMaxScaler()

df_xy[a_col] = mm_a.fit_transform(df_xy[a_col])
df_xy[s_col] = mm_s.fit_transform(df_xy[s_col])
df_xy[y_col] = mm_y.fit_transform(df_xy[y_col])
df_xy

,ARO1-DCS-FIC_98302_1,ARO1-DCS-FIC_98401_1,ARO1-DCS-AC_CTIME,ARO1-DCS-AC_STIME,ARO1-LIMS-S704-BR_INDEX,ARO1-LIMS-s704-744-C9,ARO1-LIMS-s704-744-C10+,ARO1-LIMS-S704-WATER,ARO1-LIMS-S704-TS,ARO1-DCS-AC_L2_A,ARO1-DCS-AC_L3_A,ARO1-DCS-AC_L4_A,ARO1-DCS-AC_A_FA,ARO1-DCS-AC_HF,ARO1-DCS-PX 回收率
0,0.881728,0.860078,0.315575,0.615902,0.077020,0.017049,0.0,0.056437,0.005376,0.664755,0.737276,0.863700,0.516103,0.923255,NaN
1,0.881728,0.860078,0.315575,0.615902,0.077020,0.017049,0.0,0.056437,0.005376,0.664755,0.737276,0.863700,0.516103,0.923255,NaN
2,0.881728,0.860078,0.315575,0.615902,0.077020,0.017049,0.0,0.056437,0.005376,0.664755,0.737276,0.863700,0.516103,0.923255,NaN
3,0.881728,0.860078,0.315575,0.615902,0.077020,0.017049,0.0,0.056437,0.005376,0.664755,0.737276,0.863700,0.516103,0.923255,NaN
4,0.881728,0.860078,0.315575,0.615902,0.077020,0.017049,0.0,0.056437,0.005376,0.664607,0.737276,0.863700,0.516103,0.923255,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71443,0.999273,1.000000,0.264807,0.516820,0.059343,0.015865,0.0,0.074300,0.005376,0.560594,0.737234,0.830864,0.510544,0.923255,NaN
71444,0.999273,1.000000,0.264807,0.516820,0.059343,0.015865,0.0,0.074300,0.005376,0.560594,0.737234,0.830864,0.510544,0.923255,NaN
71445,0.999273,1.000000,0.264807,0.516820,0.059343,0.015865,0.0,0.074300,0.005376,0.560594,0.737234,0.830864,0.510544,0.923255,NaN
71446,0.999273,1.000000,0.264807,0.516820,0.059343,0.015865,0.0,0.074300,0.005376,0.560594,0.737234,0.830864,0.510544,0.923255,NaN
71447,0.999273,1.000000,0.264807,0.516820,0.059343,0.015865,0.0,0.074300,0.005376,0.560594,0.737234,0.830864,0.510544,0.923255,0.966936

In [62]:
df_xy.describe().T

,count,mean,std,min,25%,50%,75%,max
ARO1-DCS-FIC_98302_1,71359.0,0.897546,0.206979,0.0,0.881728,0.987567,0.987567,1.0
ARO1-DCS-FIC_98401_1,71359.0,0.879355,0.201136,0.0,0.838470,0.965167,0.980399,1.0
ARO1-DCS-AC_CTIME,71359.0,0.298171,0.053408,0.0,0.270762,0.275462,0.324977,1.0
ARO1-DCS-AC_STIME,71359.0,0.580293,0.103760,0.0,0.528440,0.537615,0.634251,1.0
ARO1-LIMS-S704-BR_INDEX,71448.0,0.140188,0.089766,0.0,0.082071,0.121843,0.174874,1.0
ARO1-LIMS-s704-744-C9,71448.0,0.020333,0.016187,0.0,0.011603,0.017523,0.025337,1.0
ARO1-LIMS-s704-744-C10+,71448.0,0.000179,0.011182,0.0,0.000000,0.000000,0.000000,1.0
ARO1-LIMS-S704-WATER,71448.0,0.077885,0.040018,0.0,0.058630,0.070187,0.087671,1.0
ARO1-LIMS-S704-TS,71448.0,0.013144,0.026205,0.0,0.005376,0.005376,0.010753,1.0
ARO1-DCS-AC_L2_A,71359.0,0.624177,0.059092,0.0,0.574201,0.628471,0.660802,1.0
ARO1-DCS-AC_L3_A,71359.0,0.739779,0.035265,0.0,0.737234,0.737276,0.737276,1.0
ARO1-DCS-AC_L4_A,71359.0,0.847278,0.036456,0.0,0.830864,0.840200,0.868400,1.0
ARO1-DCS-AC_A_FA,71359.0,0.507716,0.055799,0.0,0.497404,0.497404,0.510544,1.0
ARO1-DCS-AC_HF,71359.0,0.921807,0.037685,0.0,0.923255,0.923255,0.923255,1.0
ARO1-DCS-PX 回收率,2888.0,0.970991,0.027306,0.0,0.969965,0.973009,0.975343,1.0

# 建立資料集 for 建模使用

In [63]:
from tqdm import tqdm_notebook as tqdm
def build_dataset(df,n=None):
    data = {
        'state':[],
        'action':[],
        'value':[],
        'idx':[],
        }
    
    for i in tqdm(range(0,len(df)-n,n)):
        curr = df.iloc[i:i+n] #一小段資料
        cond1 = np.isnan(curr[y_col].values[-1]).sum() == 0
        cond2 = np.isnan(curr[s_col+a_col].values).sum() == 0
        if cond1 & cond2: #確保這段資料無缺失值
            data['state'].append(curr[s_col].values) # 這段時間所有狀態
            data['action'].append(curr[a_col].values) # 這段時間所有操作
            data['value'].append(curr[y_col].values[-1]) # 這段時間最後一個時間點的產量
            data['idx'].append(curr.index[-1]) #這段時間最後 出料對應的時間點
    
    # reshape
    data['state'] = np.array(data['state'])
    data['action'] = np.array(data['action'])
    data['value'] = np.array(data['value'])
    
    # store mm_scaler
    data['mm_state'] = mm_s
    data['mm_action'] = mm_a
    data['mm_value'] = mm_y
    
    # store col_name
    data['state_col'] = s_col
    data['action_col'] = a_col
    data['value_col'] = y_col
    
    return data

In [64]:
import numpy as np
data = build_dataset(df_xy.iloc[df_xy[y_col].dropna(axis=0).index[0]+1:],n=get_interval(df_y,y_col[0]))

C:\Users\ricky\AppData\Local\Temp/ipykernel_14696/3492296234.py:10: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm(range(0,len(df)-n,n)):

HBox(children=(FloatProgress(value=0.0, max=2887.0), HTML(value='')))

In [65]:
data['action'].shape,data['state'].shape,data['value'].shape

((2886, 8, 5), (2886, 8, 9), (2886, 1))

In [66]:
np.isnan(data['action']).sum(),np.isnan(data['state']).sum(),np.isnan(data['value']).sum()

(0, 0, 0)

In [67]:
np.isnan(data['state']).sum()

0

In [68]:
data['state']

array([[[0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269],
        ...,
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.01075269]],

       [[0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634],
        ...,
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.06590602, 0.00537634]],

       [[0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634],
        ...,
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634],
        [0.99927344, 0.98547653, 0.27076152, ..., 0.        ,
         0.05148051, 0.00537634]],

       ...,

       [[0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634],
        ...,
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.04677746, 0.00537634]],

       [[0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        ...,
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634]],

       [[0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        ...,
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634],
        [0.99927344, 1.        , 0.26480727, ..., 0.        ,
         0.08541421, 0.00537634]]])

In [69]:
data['action']

array([[[0.58374733, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58420445, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58466158, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        ...,
        [0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452]],

       [[0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58492937, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        ...,
        [0.58690756, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58770625, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.58850495, 0.73727586, 0.83080038, 0.49740376, 0.92325452]],

       [[0.58930364, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.59010233, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.59090074, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        ...,
        [0.59127913, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.59127913, 0.73727586, 0.83080038, 0.49740376, 0.92325452],
        [0.59127913, 0.73727586, 0.83080038, 0.49740376, 0.92325452]],

       ...,

       [[0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        ...,
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452]],

       [[0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        ...,
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452]],

       [[0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        ...,
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452],
        [0.56059449, 0.73723371, 0.8308638 , 0.51054444, 0.92325452]]])

In [70]:
data['value']

array([[0.98260133],
       [0.98242097],
       [0.98244268],
       ...,
       [0.96649016],
       [0.96673966],
       [0.96694799]])

In [71]:
#保存
import joblib
print(len(data['idx']))
joblib.dump(data,'../data/dataset.pkl')

2886

['../data/dataset.pkl']